// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/button/Button.vue')['default']
    Sample: typeof import('./src/components/Sample/Sample.vue')['default']
  }
}

export {}
